using System;
using System.IO;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.Diagnostics;
using System.Globalization;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Controls.Primitives;
using System.Windows.Interop;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Threading;
using Microsoft.Win32;
using Forms=System.Windows.Forms;
namespace PCCare {
 public class Trend:FrameworkElement {
  public readonly List<double> CPU=new List<double>(),RAM=new List<double>();
  public void Add(double c,double r){CPU.Add(Math.Max(0,c));RAM.Add(r);if(CPU.Count>60){CPU.RemoveAt(0);RAM.RemoveAt(0);}InvalidateVisual();}
  protected override void OnRender(DrawingContext d){base.OnRender(d);double w=ActualWidth,h=ActualHeight;for(int i=0;i<5;i++)d.DrawLine(new Pen(new SolidColorBrush(Color.FromRgb(39,56,77)),1),new Point(0,h*i/4),new Point(w,h*i/4));Draw(d,CPU,"#71E4C4",w,h);Draw(d,RAM,"#A99BFF",w,h);}
  void Draw(DrawingContext d,List<double> values,string hex,double w,double h){var pen=new Pen((Brush)new BrushConverter().ConvertFromString(hex),2.5);for(int i=1;i<values.Count;i++)d.DrawLine(pen,new Point(w*(i-1)/59,h*(1-values[i-1]/100)),new Point(w*i/59,h*(1-values[i]/100)));}
 }
 public class MainWindow:Window {
  static Brush B(string h){return (Brush)new BrushConverter().ConvertFromString(h);}
  readonly TabControl tabs=new TabControl();readonly List<Button> navButtons=new List<Button>();readonly StackPanel nav=new StackPanel();
  readonly TextBlock status=Txt("Готово",13),subtitle=Txt("Ваш компьютер под контролем",14),cpuValue=Txt("—",30),ramValue=Txt("—",30),vramValue=Txt("—",30),diskValue=Txt("—",30),cpuHint=Txt("Первое измерение",12),ramHint=Txt("Оперативная память",12),vramHint=Txt("Ожидание NVIDIA",12),diskHint=Txt("Системный диск",12),accountText=Txt("ChatGPT не подключён",13),floatText=Txt("Измерение…",13);
  readonly ProgressBar cpuBar=new ProgressBar(),ramBar=new ProgressBar(),vramBar=new ProgressBar(),diskBar=new ProgressBar();readonly Trend trend=new Trend{Height=135,Margin=new Thickness(0,16,0,8)};
  readonly TextBox recommendations=Box(true,130),hardware=Box(true,185),gpu=Box(true,85),folder=Box(false,40),comfy=Box(false,40),report=Box(true,115),chat=Box(true,220),question=Box(false,70),health=Box(true,200),updates=Box(true,220),startup=Box(true,250),largeFolder=Box(false,40),manualModel=Box(false,40);
  readonly PasswordBox key=new PasswordBox();readonly ComboBox models=new ComboBox{MinWidth=240,DisplayMemberPath="Name"},provider=new ComboBox(),interval=new ComboBox();
  readonly CheckBox consent=new CheckBox{Content="Отправить показанный отчёт ПК вместе с вопросом"},auto=new CheckBox{Content="Фоновая очистка старых временных файлов"},protect=new CheckBox{Content="Проверять очередь ComfyUI перед фоновой очисткой"},trayOption=new CheckBox{Content="Крестик скрывает приложение в трей"},startupOption=new CheckBox{Content="Запускать PC Care Studio при входе в Windows"};
  readonly DataGrid cleanGrid=Table(),fileGrid=Table(),processGrid=Table(),largeGrid=Table();readonly TextBlock cleanSummary=Txt("Сначала выполните сканирование",15);
  readonly OpenAIClient ai=new OpenAIClient();readonly HttpClient http=new HttpClient{Timeout=TimeSpan.FromSeconds(10)};readonly Settings settings=Settings.Load();readonly DispatcherTimer timer=new DispatcherTimer();readonly Forms.NotifyIcon tray=new Forms.NotifyIcon();
  readonly List<Dictionary<string,string>> history=new List<Dictionary<string,string>>();Snapshot snapshot;Window floating;string hardwareText="Сведения ещё не получены.";bool busy,ticking,quitting,loading=true;DateTime lastAuto=DateTime.UtcNow;CancellationTokenSource requestCancellation;
  static TextBlock Txt(string text,int size){return new TextBlock{Text=text,FontSize=size,TextWrapping=TextWrapping.Wrap,Margin=new Thickness(0,0,0,8)};}
  static TextBox Box(bool read,double height){return new TextBox{IsReadOnly=read,AcceptsReturn=true,Height=height,TextWrapping=TextWrapping.Wrap,VerticalScrollBarVisibility=ScrollBarVisibility.Auto};}
  static DataGrid Table(){return new DataGrid{AutoGenerateColumns=false,CanUserAddRows=false,CanUserDeleteRows=false,SelectionMode=DataGridSelectionMode.Single,Height=300,Margin=new Thickness(0,12,0,16)};}
  Button Btn(string text,Func<Task> action,bool accent=false){var b=new Button{Content=text};if(accent){b.Background=B("#236C62");b.BorderBrush=B("#48B19B");}b.Click+=async delegate{if(busy){status.Text="Дождитесь завершения текущей операции.";return;}busy=true;b.IsEnabled=false;try{await action();}catch(OperationCanceledException){status.Text="Операция отменена.";}catch(Exception e){status.Text="Ошибка: "+e.Message;MessageBox.Show(this,e.Message,"PC Care Studio",MessageBoxButton.OK,MessageBoxImage.Information);}finally{requestCancellation=null;b.IsEnabled=true;busy=false;}};return b;}
  static Task Done(){return Task.FromResult(0);}bool Confirm(string text){return MessageBox.Show(this,text,"PC Care Studio — подтверждение",MessageBoxButton.YesNo,MessageBoxImage.Question)==MessageBoxResult.Yes;}
  static void Open(string p){Process.Start(new ProcessStartInfo(p){UseShellExecute=true});}
  WrapPanel Row(StackPanel p){var row=new WrapPanel{Margin=new Thickness(0,8,0,4)};p.Children.Add(row);return row;}
  StackPanel Page(string title,string desc){var p=new StackPanel{Margin=new Thickness(28,20,28,20)};p.Children.Add(Txt(title,28));var text=Txt(desc,14);text.Foreground=B("#96A6BC");text.Margin=new Thickness(0,0,0,18);p.Children.Add(text);int index=tabs.Items.Count;tabs.Items.Add(new TabItem{Header=title,Content=new ScrollViewer{Content=p,VerticalScrollBarVisibility=ScrollBarVisibility.Auto}});var button=new Button{Content=title,HorizontalContentAlignment=HorizontalAlignment.Left,Margin=new Thickness(0,0,0,8),Padding=new Thickness(12),Background=Brushes.Transparent,BorderThickness=new Thickness(0)};button.Click+=delegate{Select(index);};navButtons.Add(button);nav.Children.Add(button);return p;}
  void Select(int index){tabs.SelectedIndex=index;for(int i=0;i<navButtons.Count;i++){navButtons[i].Background=i==index?B("#243C46"):Brushes.Transparent;navButtons[i].Foreground=i==index?B("#71E4C4"):B("#96A6BC");}}
  Border Card(string title,TextBlock value,TextBlock hint,ProgressBar bar){var p=new StackPanel();var label=Txt(title,12);label.Foreground=B("#96A6BC");p.Children.Add(label);p.Children.Add(value);hint.Foreground=B("#96A6BC");hint.MinHeight=32;p.Children.Add(hint);p.Children.Add(bar);return new Border{Background=B("#182438"),BorderBrush=B("#2A3A51"),BorderThickness=new Thickness(1),CornerRadius=new CornerRadius(15),Padding=new Thickness(18),Margin=new Thickness(0,0,12,0),Child=p};}
  static void FileColumns(DataGrid g,bool move){g.Columns.Add(new DataGridCheckBoxColumn{Header="",Width=42,Binding=new System.Windows.Data.Binding("Selected")});g.Columns.Add(new DataGridTextColumn{Header="Файл",IsReadOnly=true,Binding=new System.Windows.Data.Binding("Source"),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});g.Columns.Add(new DataGridTextColumn{Header="Размер",IsReadOnly=true,Binding=new System.Windows.Data.Binding("Size"),Width=95});if(move)g.Columns.Add(new DataGridTextColumn{Header="Куда",IsReadOnly=true,Binding=new System.Windows.Data.Binding("Destination"),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});}
  static void Commit(DataGrid g){g.CommitEdit(DataGridEditingUnit.Cell,true);g.CommitEdit(DataGridEditingUnit.Row,true);}
  public MainWindow(){
   Title="PC Care Studio 1.0";Width=1220;Height=850;MinWidth=980;MinHeight=680;FontFamily=new FontFamily("Segoe UI");FontSize=14;Background=B("#0E1726");Foreground=B("#ECF2FA");WindowStartupLocation=WindowStartupLocation.CenterScreen;
   var root=new DockPanel();Content=root;
   var left=new DockPanel{Width=210,Background=B("#121D2E"),Margin=new Thickness(0)};DockPanel.SetDock(left,Dock.Left);root.Children.Add(left);
   var brand=new StackPanel{Margin=new Thickness(22,26,18,30)};brand.Children.Add(Txt("◈  PC CARE",23));var sub=Txt("STUDIO  /  1.0",11);sub.Foreground=B("#71E4C4");brand.Children.Add(sub);DockPanel.SetDock(brand,Dock.Top);left.Children.Add(brand);
   var footer=new StackPanel{Margin=new Thickness(18)};footer.Children.Add(Btn("Плавающая панель",()=>{ShowFloating();return Done();}));footer.Children.Add(Btn("Свернуть в трей",()=>{Hide();return Done();}));var offline=Txt("Локальная диагностика\nИИ подключается отдельно",11);offline.Foreground=B("#96A6BC");footer.Children.Add(offline);DockPanel.SetDock(footer,Dock.Bottom);left.Children.Add(footer);nav.Margin=new Thickness(12);left.Children.Add(nav);
   var content=new DockPanel();root.Children.Add(content);var top=new DockPanel{Margin=new Thickness(28,16,28,0)};subtitle.Foreground=B("#96A6BC");top.Children.Add(subtitle);DockPanel.SetDock(top,Dock.Top);content.Children.Add(top);
   var bottom=new Border{Background=B("#152236"),Padding=new Thickness(20,10,20,6),Child=status};DockPanel.SetDock(bottom,Dock.Bottom);content.Children.Add(bottom);content.Children.Add(tabs);
   var p=Page("Обзор","Живые показатели и рекомендации на основе состояния компьютера.");
   var cards=new UniformGrid{Columns=4,Margin=new Thickness(0,0,0,18)};cards.Children.Add(Card("ПРОЦЕССОР",cpuValue,cpuHint,cpuBar));cards.Children.Add(Card("ОПЕРАТИВНАЯ ПАМЯТЬ",ramValue,ramHint,ramBar));cards.Children.Add(Card("ВИДЕОПАМЯТЬ",vramValue,vramHint,vramBar));cards.Children.Add(Card("СВОБОДНО НА ДИСКЕ",diskValue,diskHint,diskBar));p.Children.Add(cards);
   p.Children.Add(Txt("Нагрузка за последние 5 минут",17));p.Children.Add(trend);var legend=Txt("● CPU      ● RAM     •     интервал 5 секунд",12);legend.Foreground=B("#96A6BC");p.Children.Add(legend);
   var row=Row(p);row.Children.Add(Btn("Проверить перед генерацией",async()=>{await Refresh();Select(0);status.Text="Измерение обновлено. Проверьте рекомендации, свободную RAM и VRAM.";},true));row.Children.Add(Btn("Сканировать мусор",Scan));row.Children.Add(Btn("Спросить ИИ",()=>{Select(5);return Done();}));
   p.Children.Add(Txt("Что можно улучшить",18));p.Children.Add(recommendations);p.Children.Add(Txt("Видеокарта • модель, VRAM МБ, GPU %, °C, драйвер",13));p.Children.Add(gpu);
   p=Page("Очистка","Сначала просмотрите список. Удаляются только старые .tmp/.temp в пользовательской папке Temp.");row=Row(p);row.Children.Add(Btn("Сканировать",Scan,true));row.Children.Add(Btn("Удалить выбранные",Clean));row.Children.Add(Btn("Выбрать всё",()=>{ChooseAll(cleanGrid,true);return Done();}));row.Children.Add(Btn("Снять выбор",()=>{ChooseAll(cleanGrid,false);return Done();}));p.Children.Add(cleanSummary);FileColumns(cleanGrid,false);p.Children.Add(cleanGrid);
   p.Children.Add(Txt("Файлы моложе 7 дней, занятые файлы, ссылки, модели и проекты пропускаются. Очистка окончательная. Автоочистка настраивается отдельно.",13));row=Row(p);row.Children.Add(Btn("Корзина Windows",()=>{Open("shell:RecycleBinFolder");return Done();}));row.Children.Add(Btn("Очистить корзину…",()=>{Core.EmptyBin(new WindowInteropHelper(this).Handle);status.Text="Операция корзины передана Windows.";return Done();}));row.Children.Add(Btn("Хранилище Windows",()=>{Open("ms-settings:storagesense");return Done();}));
   p=Page("Порядок в файлах","Фото, видео, документы, аудио и архивы — по папкам, с предварительным просмотром и отменой.");folder.Text=String.IsNullOrEmpty(settings.Folder)?Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile),"Downloads"):settings.Folder;p.Children.Add(folder);row=Row(p);row.Children.Add(Btn("Выбрать папку",()=>{ChooseFolder(folder);return Done();}));row.Children.Add(Btn("Показать план",async()=>{string path=folder.Text;fileGrid.ItemsSource=await Task.Run(()=>Core.Plan(path));Save();status.Text="План готов. Файлы ещё не перемещены.";},true));row.Children.Add(Btn("Разложить выбранные",Organize));row.Children.Add(Btn("Отменить сортировку",async()=>{if(Confirm("Вернуть неизменённые файлы последней сортировки?"))status.Text=await Task.Run(()=>Core.Undo());}));FileColumns(fileGrid,true);p.Children.Add(fileGrid);p.Children.Add(Txt("Для сортировки выберите Загрузки, Рабочий стол или их подпапку. Файлы моложе суток и совпадающие имена пропускаются. Папки программ и моделей защищены.",13));
   p.Children.Add(Txt("Найти крупные файлы",20));largeFolder.Text=folder.Text;p.Children.Add(largeFolder);row=Row(p);row.Children.Add(Btn("Выбрать папку поиска",()=>{ChooseFolder(largeFolder);return Done();}));row.Children.Add(Btn("Найти файлы ≥100 МБ",async()=>{string path=largeFolder.Text;status.Text="Ищу крупные файлы…";largeGrid.ItemsSource=await Task.Run(()=>Core.LargeFiles(path));status.Text="Показаны до 200 крупнейших файлов; обход ограничен 20 000 папок. Файлы не удалялись.";}));row.Children.Add(Btn("Показать выбранный в Проводнике",()=>{var f=largeGrid.SelectedItem as FileRow;if(f!=null)Core.OpenLocation(f.Source);return Done();}));FileColumns(largeGrid,false);largeGrid.Columns.RemoveAt(0);largeGrid.IsReadOnly=true;p.Children.Add(largeGrid);
   p=Page("Память и VRAM","Проверьте потребителей памяти и освободите ресурсы через выбранное приложение.");row=Row(p);row.Children.Add(Btn("Обновить процессы",Processes,true));row.Children.Add(Btn("Закрыть выбранное приложение",CloseProcess));row.Children.Add(Btn("Диспетчер задач",()=>{Open("taskmgr.exe");return Done();}));foreach(var col in new[]{"PID","Name","RAM"})processGrid.Columns.Add(new DataGridTextColumn{Header=col,Binding=new System.Windows.Data.Binding(col),Width=new DataGridLength(1,DataGridLengthUnitType.Star)});processGrid.IsReadOnly=true;p.Children.Add(processGrid);p.Children.Add(Txt("Закрытие выполняется обычным запросом окну приложения. Сохраните работу. Системные и фоновые процессы без окна принудительно не завершаются.",13));
   p.Children.Add(Txt("Выгрузить модели ComfyUI",20));comfy.Text=settings.Comfy;p.Children.Add(comfy);row=Row(p);row.Children.Add(Btn("Проверить очередь",async()=>{status.Text=await ComfyIdle(ComfyUri())?"ComfyUI доступен. Очередь пуста.":"ComfyUI занят: есть выполняющиеся или ожидающие задачи.";Save();}));row.Children.Add(Btn("Выгрузить модели",FreeComfy,true));p.Children.Add(Txt("Занятая очередь блокирует выгрузку. Драйвер, рабочий стол и другие приложения продолжат использовать VRAM; следующая генерация заново загрузит модели.",13));
   p=Page("Диагностика","Оборудование, накопители, автозагрузка и обновления. Данные считываются с вашего ПК.");row=Row(p);row.Children.Add(Btn("Обновить оборудование",async()=>{hardwareText=await Task.Run(()=>Core.Hardware());hardware.Text=hardwareText;status.Text="Оборудование обновлено.";},true));row.Children.Add(Btn("Сохранить отчёт",Export));p.Children.Add(hardware);
   p.Children.Add(Txt("Состояние накопителей",20));row=Row(p);row.Children.Add(Btn("Проверить накопители",async()=>{health.Text="Проверка…";health.Text=await Core.Health();}));p.Children.Add(health);p.Children.Add(Txt("HealthStatus — оценка Windows. Это не полный SMART-тест поверхности и не гарантия исправности диска.",12));
   p.Children.Add(Txt("Доступные обновления Windows",20));row=Row(p);row.Children.Add(Btn("Проверить обновления",async()=>{updates.Text="Windows ищет обновления. Это может занять до двух минут…";updates.Text=await Core.Updates();}));row.Children.Add(Btn("Открыть Windows Update",()=>{Open("ms-settings:windowsupdate");return Done();}));row.Children.Add(Btn("Драйвер NVIDIA",()=>{Open("https://www.nvidia.com/Download/index.aspx");return Done();}));p.Children.Add(updates);
   p.Children.Add(Txt("Автозагрузка",20));row=Row(p);row.Children.Add(Btn("Показать автозагрузку",async()=>{startup.Text=await Task.Run(()=>Core.Startup());}));row.Children.Add(Btn("Настроить в Windows",()=>{Open("ms-settings:startupapps");return Done();}));p.Children.Add(startup);
   p=Page("ИИ-помощник","Обсудите диагностику с ИИ. Отправка отчёта — по вашему выбору; изменения выполняются отдельными кнопками.");provider.Items.Add("ChatGPT — вход через аккаунт");provider.Items.Add("OpenAI API — собственный ключ");provider.SelectedIndex=ai.Account==null?1:0;p.Children.Add(provider);p.Children.Add(accountText);row=Row(p);row.Children.Add(Btn("Continue with ChatGPT",SignIn,true));row.Children.Add(Btn("Выйти из ChatGPT",SignOut));row.Children.Add(Btn("Открыть обычный ChatGPT",()=>{Open("https://chatgpt.com/");return Done();}));p.Children.Add(Txt("Вход через ChatGPT зависит от доступности интеграции для аккаунта. Пароль вводится только на сайте OpenAI. Токены защищены Windows DPAPI.",12));p.Children.Add(Txt("API-ключ (только для режима API, хранится до закрытия)",13));p.Children.Add(key);
   row=Row(p);row.Children.Add(Btn("Загрузить доступные модели",LoadModels));p.Children.Add(models);p.Children.Add(Txt("Или введите ID модели вручную",12));manualModel.Text=settings.Model;p.Children.Add(manualModel);models.SelectionChanged+=delegate{var m=models.SelectedItem as ModelItem;if(m!=null)manualModel.Text=m.Id;};
   p.Children.Add(Txt("Отчёт, который будет отправлен при включённой галочке",13));p.Children.Add(report);p.Children.Add(consent);p.Children.Add(chat);question.Text="Что мешает быстрой работе ПК и какие 3 проверки сделать перед генерацией в ComfyUI?";p.Children.Add(question);row=Row(p);row.Children.Add(Btn("Отправить",Ask,true));var cancel=new Button{Content="Остановить запрос"};cancel.Click+=delegate{if(requestCancellation!=null)requestCancellation.Cancel();};row.Children.Add(cancel);row.Children.Add(Btn("Новый диалог",()=>{history.Clear();chat.Clear();status.Text="История диалога очищена.";return Done();}));row.Children.Add(Btn("Копировать отчёт",()=>{Clipboard.SetText(Report());status.Text="Отчёт скопирован для вставки в ChatGPT.";return Done();}));
   p=Page("Настройки","Фоновая работа включается вами. Настройки сохраняются локально.");p.Children.Add(auto);interval.Items.Add(15);interval.Items.Add(30);interval.Items.Add(60);interval.SelectedItem=new[]{15,30,60}.Contains(settings.Minutes)?settings.Minutes:30;p.Children.Add(Txt("Интервал автоочистки, минут",13));p.Children.Add(interval);protect.IsChecked=settings.ProtectComfy;p.Children.Add(protect);trayOption.IsChecked=settings.Tray;p.Children.Add(trayOption);startupOption.IsChecked=Core.AutoStarts();p.Children.Add(startupOption);
   row=Row(p);row.Children.Add(Btn("Сохранить настройки",()=>{Save();Core.AutoStart(startupOption.IsChecked==true);status.Text="Настройки сохранены.";return Done();},true));row.Children.Add(Btn("Журнал операций",()=>{Directory.CreateDirectory(Core.Data);Open(Core.Data);return Done();}));row.Children.Add(Btn("Завершить программу",()=>{Quit();return Done();}));p.Children.Add(Txt("Автоочистка работает только при низкой измеренной нагрузке и пропускается, если GPU недоступен. При включённой защите ComfyUI нужна связь с сервером. Очистка реестра, сброс драйвера и отключение защиты Windows не выполняются.",13));
   auto.IsChecked=settings.AutoClean;auto.Checked+=delegate{if(!loading&&!Confirm("Разрешить окончательное удаление старых .tmp/.temp в фоне? Настройка сохранится после нажатия «Сохранить настройки»."))auto.IsChecked=false;lastAuto=DateTime.UtcNow;};
   provider.SelectionChanged+=delegate{models.ItemsSource=null;history.Clear();chat.Clear();};UpdateAccount();Select(0);loading=false;
   tray.Icon=System.Drawing.SystemIcons.Application;tray.Text="PC Care Studio";tray.Visible=true;tray.DoubleClick+=delegate{Dispatcher.Invoke(new Action(Restore));};var menu=new Forms.ContextMenuStrip();menu.Items.Add("Открыть",null,delegate{Dispatcher.Invoke(new Action(Restore));});menu.Items.Add("Плавающая панель",null,delegate{Dispatcher.Invoke(new Action(ShowFloating));});menu.Items.Add("Выход",null,delegate{Dispatcher.Invoke(new Action(Quit));});tray.ContextMenuStrip=menu;
   timer.Interval=TimeSpan.FromSeconds(5);timer.Tick+=async delegate{if(ticking||quitting)return;ticking=true;try{await Refresh();if(!busy)await BackgroundClean();}catch(Exception e){status.Text="Мониторинг: "+e.Message;}finally{ticking=false;}};
   Loaded+=async delegate{ticking=true;try{await Refresh();hardwareText=await Task.Run(()=>Core.Hardware());hardware.Text=hardwareText;await Processes();}catch(Exception e){status.Text=e.Message;}finally{ticking=false;timer.Start();}if(Environment.GetCommandLineArgs().Contains("--tray"))Hide();};
   Closing+=delegate(object sender,System.ComponentModel.CancelEventArgs e){if(!quitting&&trayOption.IsChecked==true){e.Cancel=true;Hide();tray.ShowBalloonTip(2000,"PC Care Studio","Программа работает в трее. Для завершения выберите «Выход».",Forms.ToolTipIcon.Info);}};
   Closed+=delegate{quitting=true;timer.Stop();if(requestCancellation!=null)requestCancellation.Cancel();if(floating!=null)floating.Close();tray.Dispose();ai.Dispose();http.Dispose();Application.Current.Shutdown();};
  }
  void Restore(){Show();WindowState=WindowState.Normal;Activate();}void Quit(){if(busy&&!Confirm("Операция ещё выполняется. Завершить программу? Незавершённый ответ ИИ будет потерян."))return;quitting=true;Close();}
  void Save(){settings.Comfy=comfy.Text.Trim();settings.Model=manualModel.Text.Trim();settings.Folder=folder.Text;settings.AutoClean=auto.IsChecked==true;settings.ProtectComfy=protect.IsChecked==true;settings.Tray=trayOption.IsChecked==true;settings.Minutes=interval.SelectedItem is int?(int)interval.SelectedItem:30;settings.Save();}
  void ChooseFolder(TextBox field){using(var d=new Forms.FolderBrowserDialog{Description="Выберите папку",SelectedPath=Directory.Exists(field.Text)?field.Text:"",ShowNewFolderButton=false})if(d.ShowDialog()==Forms.DialogResult.OK)field.Text=d.SelectedPath;}
  void ChooseAll(DataGrid grid,bool value){Commit(grid);var rows=grid.ItemsSource as List<FileRow>;if(rows!=null){foreach(var r in rows)r.Selected=value;grid.Items.Refresh();}}
  async Task Scan(){Select(1);status.Text="Сканирование временных файлов…";var rows=await Task.Run(()=>Core.Scan());cleanGrid.ItemsSource=rows;cleanSummary.Text=rows.Count+" файлов • "+Core.Size(rows.Sum(x=>x.Bytes));status.Text="Сканирование завершено. Проверьте список.";}
  async Task Clean(){Commit(cleanGrid);var rows=cleanGrid.ItemsSource as List<FileRow>;if(rows==null){await Scan();return;}int count=rows.Count(x=>x.Selected);if(count==0)return;if(!Confirm("Окончательно удалить "+count+" выбранных временных файлов?"))return;status.Text=await Task.Run(()=>Core.Clean(rows));cleanGrid.ItemsSource=null;cleanSummary.Text=status.Text;}
  async Task Organize(){Commit(fileGrid);var rows=fileGrid.ItemsSource as List<FileRow>;if(rows==null||!rows.Any(x=>x.Selected))return;if(Confirm("Переместить "+rows.Count(x=>x.Selected)+" файлов в папку «Разобрано»?")){status.Text=await Task.Run(()=>Core.Organize(rows));fileGrid.ItemsSource=null;}}
  async Task Processes(){processGrid.ItemsSource=await Task.Run(()=>Core.Processes());}
  async Task CloseProcess(){var row=processGrid.SelectedItem as ProcessRow;if(row==null)return;using(var p=Process.GetProcessById(row.PID)){if(p.Id==Process.GetCurrentProcess().Id||p.StartTime.ToUniversalTime()!=row.Started||p.MainWindowHandle==IntPtr.Zero)throw new Exception("Нельзя закрыть этот процесс: нет обычного окна или процесс изменился.");if(Confirm("Попросить «"+row.Name+"» закрыться? Сначала сохраните работу.")){status.Text=p.CloseMainWindow()?"Приложению отправлен запрос закрытия. Подтвердите сохранение в его окне.":"Приложение не приняло запрос закрытия.";}}await Processes();}
  async Task Refresh(){snapshot=await Core.ReadStats();cpuValue.Text=snapshot.CPU<0?"—":snapshot.CPU.ToString("0")+"%";cpuHint.Text="Загрузка процессора";cpuBar.Value=Math.Max(0,snapshot.CPU);ramValue.Text=snapshot.Load+"%";ramHint.Text=Core.Size(snapshot.Total-snapshot.Free)+" из "+Core.Size(snapshot.Total);ramBar.Value=snapshot.Load;gpu.Text=snapshot.GPU;
   var fields=snapshot.GPU.Split('\n')[0].Split(',');double used,total;if(fields.Length>=6&&Double.TryParse(fields[1],NumberStyles.Float,CultureInfo.InvariantCulture,out used)&&Double.TryParse(fields[2],NumberStyles.Float,CultureInfo.InvariantCulture,out total)&&total>0){vramValue.Text=(used/1024).ToString("0.0")+" ГБ";vramHint.Text="из "+(total/1024).ToString("0.0")+" ГБ • GPU "+fields[3].Trim()+"%";vramBar.Value=100*used/total;}else{vramValue.Text="—";vramHint.Text="Нет данных NVIDIA";vramBar.Value=0;}
   try{var d=new DriveInfo(Path.GetPathRoot(Environment.SystemDirectory));diskValue.Text=Core.Size(d.AvailableFreeSpace);diskHint.Text=d.Name+" • из "+Core.Size(d.TotalSize);diskBar.Value=100.0*d.AvailableFreeSpace/d.TotalSize;}catch{diskValue.Text="—";}
   recommendations.Text=Core.Advice(snapshot);trend.Add(snapshot.CPU,snapshot.Load);subtitle.Text="Обновлено "+DateTime.Now.ToString("HH:mm:ss")+"   •   Локальная диагностика";floatText.Text="RAM "+snapshot.Load+"%   CPU "+cpuValue.Text+"\nVRAM "+vramValue.Text+"  "+vramHint.Text;report.Text=Report();}
  string Report(){if(snapshot==null)return "Дождитесь измерения.";return "PC Care Studio 1.0 • "+DateTime.Now.ToString("s")+"\nCPU: "+cpuValue.Text+"; RAM: "+ramHint.Text+" ("+snapshot.Load+"%)\nNVIDIA (модель, VRAM занято/всего МБ, GPU %, °C, драйвер): "+snapshot.GPU+"\n"+snapshot.Disks+"\n"+hardwareText+"\n"+Core.Advice(snapshot);}
  Task Export(){var d=new SaveFileDialog{Filter="Текстовый отчёт|*.txt",FileName="PC-Care-report.txt"};if(d.ShowDialog(this)==true)File.WriteAllText(d.FileName,Report()+"\n\nНакопители:\n"+health.Text+"\n\nОбновления:\n"+updates.Text,Encoding.UTF8);return Done();}
  Uri ComfyUri(){Uri u;if(!Uri.TryCreate(comfy.Text.Trim().TrimEnd('/')+"/",UriKind.Absolute,out u)||(u.Scheme!="http"&&u.Scheme!="https")||!String.IsNullOrEmpty(u.UserInfo))throw new Exception("Некорректный адрес ComfyUI.");return u;}
  async Task<bool> ComfyIdle(Uri u){using(var response=await http.GetAsync(new Uri(u,"queue"))){response.EnsureSuccessStatusCode();var q=Core.Json.Deserialize<Dictionary<string,object>>(await response.Content.ReadAsStringAsync());return q.ContainsKey("queue_running")&&q.ContainsKey("queue_pending")&&((System.Collections.ICollection)q["queue_running"]).Count==0&&((System.Collections.ICollection)q["queue_pending"]).Count==0;}}
  async Task FreeComfy(){var u=ComfyUri();if(!await ComfyIdle(u))throw new Exception("Очередь ComfyUI не пуста. Дождитесь окончания генерации.");if(!Confirm("Выгрузить модели ComfyUI? Следующая генерация будет загружать их повторно."))return;if(!await ComfyIdle(u))throw new Exception("В ComfyUI появилась задача; выгрузка отменена.");using(var r=await http.PostAsync(new Uri(u,"free"),new StringContent("{\"unload_models\":true,\"free_memory\":true}",Encoding.UTF8,"application/json"))){r.EnsureSuccessStatusCode();status.Text="ComfyUI принял запрос. Проверьте изменение занятой VRAM.";}Save();}
  async Task BackgroundClean(){int minutes=interval.SelectedItem is int?(int)interval.SelectedItem:30;if(auto.IsChecked!=true||DateTime.UtcNow-lastAuto<TimeSpan.FromMinutes(minutes))return;lastAuto=DateTime.UtcNow;if(snapshot==null||snapshot.CPU<0||snapshot.CPU>40||snapshot.Load>85)return;foreach(string l in snapshot.GPU.Split('\n')){double use;var f=l.Split(',');if(f.Length<6||!Double.TryParse(f[3],NumberStyles.Float,CultureInfo.InvariantCulture,out use)||use>30){status.Text="Автоочистка отложена: GPU занят или данные недоступны.";return;}}
   // Claim the action gate before awaiting a queue check so manual actions cannot race it.
   busy=true;try{if(protect.IsChecked==true){try{if(!await ComfyIdle(ComfyUri()))return;}catch{status.Text="Автоочистка отложена: нет связи с ComfyUI.";return;}}status.Text=await Task.Run(()=>Core.Clean(Core.Scan()));cleanGrid.ItemsSource=null;}finally{busy=false;}}
  void UpdateAccount(){accountText.Text=ai.Account==null?"ChatGPT не подключён":("Аккаунт: "+(String.IsNullOrEmpty(ai.Account.Email)?"подключён":ai.Account.Email));}
  async Task SignIn(){using(requestCancellation=new CancellationTokenSource()){status.Text="Завершите вход на сайте OpenAI. Кнопка остановки отменяет ожидание.";await ai.SignIn(requestCancellation.Token);provider.SelectedIndex=0;UpdateAccount();status.Text="ChatGPT подключён. Загрузите список моделей.";}requestCancellation=null;}
  async Task SignOut(){if(!Confirm("Выйти из ChatGPT и удалить сохранённые токены на этом ПК?"))return;bool revoked=await ai.SignOut(CancellationToken.None);models.ItemsSource=null;history.Clear();chat.Clear();UpdateAccount();status.Text=revoked?"Выполнен выход из ChatGPT.":"Локальный выход выполнен; отзыв на сервере не подтверждён. Отключите приложение в настройках ChatGPT.";}
  async Task<string> Access(CancellationToken ct){if(provider.SelectedIndex==0)return await ai.Token(ct);if(String.IsNullOrWhiteSpace(key.Password))throw new Exception("Введите API-ключ или выберите вход через ChatGPT.");return key.Password.Trim();}
  async Task LoadModels(){using(requestCancellation=new CancellationTokenSource()){string token=await Access(requestCancellation.Token);models.ItemsSource=await ai.Models(token,requestCancellation.Token);status.Text="Список моделей получен. Выберите текстовую модель для диалога.";}requestCancellation=null;}
  async Task Ask(){if(String.IsNullOrWhiteSpace(manualModel.Text)||String.IsNullOrWhiteSpace(question.Text))throw new Exception("Выберите модель и напишите вопрос.");if(!Confirm("Отправить вопрос"+(consent.IsChecked==true?", показанный отчёт ПК":"")+" и историю этого диалога в OpenAI? Применяются лимиты выбранного способа подключения."))return;string input=question.Text+(consent.IsChecked==true?"\n\nОтчёт:\n"+Report():"");string asked=question.Text;bool plan=provider.SelectedIndex==0;using(requestCancellation=new CancellationTokenSource(TimeSpan.FromMinutes(3))){try{string token=await Access(requestCancellation.Token);chat.AppendText("\n\nВы: "+asked+"\nИИ: ");string answer=await ai.Ask(token,manualModel.Text.Trim(),input,plan,history,delta=>{chat.AppendText(delta);chat.ScrollToEnd();},requestCancellation.Token);history.Add(new Dictionary<string,string>{{"role","user"},{"content",input}});history.Add(new Dictionary<string,string>{{"role","assistant"},{"content",answer}});while(history.Count>8)history.RemoveAt(0);Save();status.Text="Ответ завершён. ИИ не выполнял действий на ПК.";}catch{chat.AppendText("\n[Ответ не завершён]");throw;}finally{requestCancellation=null;}}}
  void ShowFloating(){if(floating!=null){floating.Activate();return;}floating=new Window{Title="PC Care • монитор",Width=350,Height=310,MinWidth=280,MinHeight=200,Topmost=true,WindowStyle=WindowStyle.ToolWindow,Background=B("#121D2E"),Foreground=Foreground,ShowInTaskbar=false};var p=new StackPanel{Margin=new Thickness(16)};p.Children.Add(Txt("◈  PC CARE",20));p.Children.Add(floatText);p.Children.Add(Btn("Сканировать и очистить",async()=>{Restore();await Scan();}));p.Children.Add(Btn("Выгрузить модели ComfyUI",FreeComfy));p.Children.Add(Btn("ИИ-помощник",()=>{Restore();Select(5);return Done();}));floating.Content=new ScrollViewer{Content=p};floating.Closed+=delegate{floating=null;};floating.Show();}
  public async Task SmokeTest(string directory){Directory.CreateDirectory(directory);await Task.Delay(2000);for(int i=0;i<tabs.Items.Count;i++){Select(i);UpdateLayout();await Task.Delay(150);if(i==0||i==1||i==5){var bmp=new RenderTargetBitmap((int)ActualWidth,(int)ActualHeight,96,96,PixelFormats.Pbgra32);bmp.Render(this);var encoder=new PngBitmapEncoder();encoder.Frames.Add(BitmapFrame.Create(bmp));using(var s=File.Create(Path.Combine(directory,"screen-"+i+".png")))encoder.Save(s);}}Select(0);quitting=true;Close();}
 }
}
